#include "input_map.h"
#include "file.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
static InputMapAction *Find(InputMap *m,const char *n){for(size_t i=0;m&&i<m->count;i++)if(!strcmp(m->actions[i].name,n))return&m->actions[i];return NULL;}
bool InputMapInit(InputMap *m,const InputMapDefinition *d,size_t n){if(!m||(!d&&n))return false;*m=(InputMap){0};m->actions=calloc(n,sizeof*m->actions);if(n&&!m->actions)return false;for(size_t i=0;i<n;i++){if(!d[i].name||!d[i].bindings||strlen(d[i].name)>=CORE_INPUT_ACTION_NAME||d[i].count>CORE_INPUT_ACTION_BINDINGS){InputMapFree(m);return false;}for(size_t j=0;j<i;j++)if(!strcmp(m->actions[j].name,d[i].name)){InputMapFree(m);return false;}strcpy(m->actions[i].name,d[i].name);m->actions[i].count=d[i].count;memcpy(m->actions[i].defaults,d[i].bindings,d[i].count*sizeof*d[i].bindings);memcpy(m->actions[i].bindings,d[i].bindings,d[i].count*sizeof*d[i].bindings);}m->count=n;return true;}
void InputMapFree(InputMap*m){if(m){free(m->actions);*m=(InputMap){0};}}
InputAction InputMapActionGet(const InputMap*m,const char*n){InputMapAction*a=Find((InputMap*)m,n);return a?(InputAction){a->bindings,a->count}:(InputAction){0};}
bool InputMapSet(InputMap*m,const char*n,size_t slot,InputBinding v,const char**conflict){InputMapAction*a=Find(m,n);if(conflict)*conflict=NULL;if(!a||slot>=a->count||(v.type!=INPUT_KEY&&v.type!=INPUT_MOUSE_BUTTON)||v.code<0)return false;for(size_t i=0;i<m->count;i++)for(size_t j=0;j<m->actions[i].count;j++)if(&m->actions[i]!=a&&m->actions[i].bindings[j].type==v.type&&m->actions[i].bindings[j].code==v.code){if(conflict)*conflict=m->actions[i].name;return false;}a->bindings[slot]=v;return true;}
bool InputMapReset(InputMap*m,const char*n){InputMapAction*a=Find(m,n);if(!a)return false;memcpy(a->bindings,a->defaults,a->count*sizeof*a->bindings);return true;}
bool InputMapWrite(const InputMap*m,const char*path){CoreAtomicFile a;FILE*f=CoreAtomicBegin(&a,path);if(!f)return false;bool ok=fprintf(f,"input-map 1\n")>0;for(size_t i=0;ok&&i<m->count;i++)for(size_t j=0;j<m->actions[i].count;j++)ok=fprintf(f,"%s %zu %d %d\n",m->actions[i].name,j,m->actions[i].bindings[j].type,m->actions[i].bindings[j].code)>0;return CoreAtomicCommit(&a,ok);}
bool InputMapRead(InputMap*m,const char*path){char*t=CoreReadFile(path);if(!t)return false;char*line=strtok(t,"\n");bool ok=line&&!strcmp(line,"input-map 1");InputMapAction*copy=ok&&m->count?malloc(m->count*sizeof*copy):NULL;if(ok&&m->count&&!copy)ok=false;if(ok&&m->count)memcpy(copy,m->actions,m->count*sizeof*copy);while(ok&&(line=strtok(NULL,"\n"))){char n[CORE_INPUT_ACTION_NAME];size_t s;int type,code;if(sscanf(line,"%47s %zu %d %d",n,&s,&type,&code)!=4){ok=false;break;}InputMapAction*a=NULL;for(size_t fi=0;fi<m->count;fi++)if(!strcmp(copy[fi].name,n)){a=&copy[fi];break;}if(!a||s>=a->count||(type!=INPUT_KEY&&type!=INPUT_MOUSE_BUTTON)||code<0){ok=false;break;}a->bindings[s]=(InputBinding){type,code};}for(size_t ai=0;ok&&ai<m->count;ai++)for(size_t aj=0;ok&&aj<copy[ai].count;aj++)for(size_t ak=ai+1;ok&&ak<m->count;ak++)for(size_t al=0;al<copy[ak].count;al++)if(copy[ai].bindings[aj].type==copy[ak].bindings[al].type&&copy[ai].bindings[aj].code==copy[ak].bindings[al].code){ok=false;break;}if(ok)for(size_t i=0;i<m->count;i++)memcpy(m->actions[i].bindings,copy[i].bindings,sizeof m->actions[i].bindings);free(copy);CoreFreeFile(t);return ok;}
bool InputMapCapture(const EngineInput*i,InputBinding*b){if(!i||!b)return false;for(int k=0;k<CORE_KEY_COUNT;k++)if(i->pressed[k]){*b=(InputBinding){INPUT_KEY,k};return true;}for(int k=0;k<CORE_MOUSE_BUTTON_COUNT;k++)if(i->mousePressed[k]){*b=(InputBinding){INPUT_MOUSE_BUTTON,k};return true;}return false;}
bool InputMapRebindButton(UiContext*ui,UiRect r,InputMap*m,InputMapRebind*x,const EngineInput*i){if(!ui||!m||!x)return false;char label[80];snprintf(label,sizeof label,"%s",x->active?"Press a key...":x->action?x->action:"Bind");if(!x->active&&UiButton(ui,r,label)){x->active=true;return false;}if(!x->active)return false;if(i->pressed[KEY_ESCAPE]){x->active=false;return false;}InputBinding b;if(!InputMapCapture(i,&b))return false;x->active=false;return InputMapSet(m,x->action,x->binding,b,NULL);}
