#include "save.h"
#include "file.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
static const CoreSaveField *Field(const CoreSaveField*f,size_t n,const char*name){for(size_t i=0;i<n;i++)if(!strcmp(f[i].name,name))return&f[i];return NULL;}
bool CoreSaveWrite(const char*path,int version,const void*state,const CoreSaveField*f,size_t n){if(!path||version<1||!state||(!f&&n))return false;CoreAtomicFile a;FILE*out=CoreAtomicBegin(&a,path);if(!out)return false;bool ok=fprintf(out,"trench-save %d\n",version)>0;for(size_t i=0;ok&&i<n;i++){const char*p=(const char*)state+f[i].offset;if(!f[i].name||strchr(f[i].name,' ')||!f[i].size){ok=false;break;}if(f[i].type==CORE_SAVE_INT)ok=fprintf(out,"%s i %d\n",f[i].name,*(const int*)p)>0;else if(f[i].type==CORE_SAVE_FLOAT)ok=isfinite(*(const float*)p)&&fprintf(out,"%s f %.9g\n",f[i].name,(double)*(const float*)p)>0;else if(f[i].type==CORE_SAVE_BOOL)ok=fprintf(out,"%s b %d\n",f[i].name,*(const bool*)p?1:0)>0;else ok=strchr(p,'\n')==NULL&&fprintf(out,"%s s %s\n",f[i].name,p)>0;}return CoreAtomicCommit(&a,ok);}
bool CoreSaveRead(const char*path,int version,void*state,const CoreSaveField*f,size_t n,CoreSaveMigrateFn migrate,void*user){char*t=CoreReadFile(path);if(!t||!state){CoreFreeFile(t);return false;}char*line=strtok(t,"\n");int from=0;bool ok=line&&sscanf(line,"trench-save %d",&from)==1&&from>0;while(ok&&(line=strtok(NULL,"\n"))){char name[64],kind;char value[512];if(sscanf(line,"%63s %c %511[^\n]",name,&kind,value)!=3){ok=false;break;}const CoreSaveField*x=Field(f,n,name);char*p=x?(char*)state+x->offset:NULL;if(!x||(kind=='i'&&x->type!=CORE_SAVE_INT)||(kind=='f'&&x->type!=CORE_SAVE_FLOAT)||(kind=='b'&&x->type!=CORE_SAVE_BOOL)||(kind=='s'&&x->type!=CORE_SAVE_STRING)){ok=false;break;}if(kind=='i')ok=sscanf(value,"%d",(int*)p)==1;else if(kind=='f')ok=sscanf(value,"%f",(float*)p)==1&&isfinite(*(float*)p);else if(kind=='b')ok=(!strcmp(value,"0")||!strcmp(value,"1"));else ok=strlen(value)<x->size;if(kind=='b')*(bool*)p=value[0]=='1';if(kind=='s'&&ok)strcpy(p,value);}if(ok&&from!=version)ok=migrate&&migrate(state,from,version,user);CoreFreeFile(t);return ok;}
