#!/usr/bin/env python3
"""Generate checked-in Godot-style XML API references from public C header comments.

The public declaration is the source of truth. Each manifest symbol needs a Doxygen-style comment
immediately above it with @brief, one @param per parameter, and @return. This intentionally parses
only ordinary C99 function declarations: a header needing more syntax should use a real C parser
before it is added to the manifest.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET


ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "docs/api/manifest.json"


def fail(message: str) -> None:
    raise ValueError(message)


def clean_comment(raw: str) -> list[str]:
    return [re.sub(r"^\s*\*?\s?", "", line).rstrip() for line in raw.splitlines()]


def parse_comment(raw: str, symbol: str, parameters: list[tuple[str, str]]) -> tuple[str, str, dict[str, str], str]:
    lines = clean_comment(raw)
    tags: dict[str, str] = {}
    body: list[str] = []
    current: str | None = None
    for line in lines:
        match = re.match(r"@(brief|param|return)\s+(.+)", line)
        if match:
            kind, value = match.groups()
            if kind == "param":
                parts = value.split(None, 1)
                if len(parts) != 2:
                    fail(f"{symbol}: @param needs a name and description")
                key, value = f"param:{parts[0]}", parts[1]
            else:
                key = kind
            if key in tags:
                fail(f"{symbol}: duplicate @{kind}")
            tags[key] = value.strip()
            current = key
        elif not line.strip():
            current = None
        else:
            if current:
                tags[current] += " " + line.strip()
            else:
                body.append(line.strip())
    if not tags.get("brief"):
        fail(f"{symbol}: missing @brief")
    if not tags.get("return"):
        fail(f"{symbol}: missing @return")
    for _, name in parameters:
        if f"param:{name}" not in tags:
            fail(f"{symbol}: missing @param {name}")
    return tags["brief"], " ".join(body) or tags["brief"], tags, tags["return"]


def declaration(source: str, symbol: str) -> tuple[str, list[tuple[str, str]], str]:
    match = re.search(rf"(?m)^[ \t]*(?P<decl>(?P<return>[^;{{}}()\n]+?)\s*{symbol}\s*\((?P<args>[^()]*)\)\s*;)", source, re.S)
    if not match:
        fail(f"{symbol}: no ordinary function declaration found")
    before = source[:match.start()]
    comment_start = before.rfind("/**")
    comment = (re.match(r"/\*\*(?P<comment>.*?)\*/\s*$", before[comment_start:], re.S)
               if comment_start >= 0 else None)
    if not comment:
        fail(f"{symbol}: needs a /** documentation block immediately above its declaration")
    args = match.group("args").strip()
    parameters: list[tuple[str, str]] = []
    if args and args != "void":
        for argument in args.split(","):
            argument = argument.strip()
            name = re.search(r"([A-Za-z_]\w*)\s*$", argument)
            if not name:
                fail(f"{symbol}: cannot read parameter name from {argument!r}")
            parameters.append((argument[:name.start()].strip(), name.group(1)))
    return match.group("return").strip(), parameters, comment.group("comment")


def reference(item: dict[str, object]) -> bytes:
    source_path = ROOT / str(item["source"])
    source = source_path.read_text(encoding="utf-8")
    root = ET.Element("class", {"name": str(item["name"]), "source": str(item["source"]), "generated": "true"})
    symbols = [str(symbol) for symbol in item["symbols"]]
    ET.SubElement(root, "brief_description").text = f"Generated reference for {item['name']}."
    ET.SubElement(root, "description").text = "Generated from Doxygen-style documentation blocks in the named public header. Do not edit this file by hand."
    methods = ET.SubElement(root, "methods")
    for symbol in symbols:
        returns, parameters, comment = declaration(source, symbol)
        brief, description, tags, return_description = parse_comment(comment, symbol, parameters)
        method = ET.SubElement(methods, "method", {"name": symbol, "brief": brief})
        returned = ET.SubElement(method, "return", {"type": returns})
        ET.SubElement(returned, "description").text = return_description
        for parameter_type, parameter_name in parameters:
            parameter = ET.SubElement(method, "param", {"name": parameter_name, "type": parameter_type})
            ET.SubElement(parameter, "description").text = tags[f"param:{parameter_name}"]
        ET.SubElement(method, "description").text = description
    ET.indent(root, space="  ")
    return b'<?xml version="1.0" encoding="UTF-8"?>\n' + ET.tostring(root, encoding="utf-8") + b"\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="write generated XML references")
    mode.add_argument("--check", action="store_true", help="fail if XML is stale or comments are incomplete")
    args = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    try:
        for item in manifest["references"]:
            output = ROOT / str(item["output"])
            generated = reference(item)
            if args.write:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_bytes(generated)
                print(f"API docs: wrote {output.relative_to(ROOT)}")
            elif not output.is_file() or output.read_bytes() != generated:
                fail(f"{output.relative_to(ROOT)} is stale; run make api-docs-update")
            else:
                print(f"API docs: PASS {output.relative_to(ROOT)}")
    except (OSError, ValueError, KeyError, json.JSONDecodeError) as error:
        print(f"API docs: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
