#!/usr/bin/env python3
"""Generate a machine-readable and human-readable script API from its binding table."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROW = re.compile(
    r'SCRIPT_BINDING\(\s*(\w+)\s*,\s*"([^"]+)"\s*,\s*(SCRIPT_\w+)\s*,\s*"([^"]*)"\s*,\s*'
    r'\(\s*SCRIPT_NONE\s*((?:,\s*SCRIPT_\w+)*)\s*\)\s*\)',
    re.S,
)


def bindings(path: Path) -> list[dict[str, object]]:
    result = []
    for identifier, name, returns, description, raw_arguments in ROW.findall(
        path.read_text(encoding="utf-8")
    ):
        arguments = [
            item.strip().removeprefix("SCRIPT_").lower()
            for item in raw_arguments.split(",")
            if item.strip()
        ]
        result.append(
            {
                "id": identifier,
                "name": name,
                "returns": returns.removeprefix("SCRIPT_").lower(),
                "arguments": arguments,
                "description": description,
            }
        )
    if not result:
        raise ValueError(f"no SCRIPT_BINDING rows found in {path}")
    return result


def markdown(api: list[dict[str, object]]) -> str:
    lines = [
        "# Script API",
        "",
        "Generated from `gameplay/script/script_api.def`; do not edit this file.",
        "",
        "| Call | Returns | Arguments | Description |",
        "| --- | --- | --- | --- |",
    ]
    for binding in api:
        arguments = ", ".join(binding["arguments"]) or "—"
        lines.append(
            f'| `{binding["name"]}` | `{binding["returns"]}` | `{arguments}` | '
            f'{binding["description"]} |'
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--format", choices=("json", "markdown"), required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    try:
        api = bindings(args.input)
        args.out.parent.mkdir(parents=True, exist_ok=True)
        content = (
            json.dumps({"bindings": api}, indent=2) + "\n"
            if args.format == "json"
            else markdown(api)
        )
        args.out.write_text(content, encoding="utf-8")
    except (OSError, ValueError) as error:
        parser.error(str(error))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
